"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$all'

[character]
success_symbol = '[á›Š](bold green)'
error_symbol = '[ášº](bold red)'

[aws]
format = 'on [$symbol$profile($region )]($style) '
symbol = 'â˜ï¸'
region_aliases = { ap-northeast-1 = "ğŸ¯" }
profile_aliases = { development = "dev", production = "prd" }

